{"timestamp":"2025-07-03T17:33:34.297377","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-03T17:33:34.297801","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/rag_reporting_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-03T17:33:35.187785Z","level":"info","event":"Iniciando RAG para la consulta: 'Resume los resultados financieros clave y la estrategia de negocio.'","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-03T17:33:39.127421","level":"info","event":"Use pytorch device_name: cpu","logger":"sentence_transformers.SentenceTransformer"}
{"timestamp":"2025-07-03T17:33:39.127520","level":"info","event":"Load pretrained SentenceTransformer: all-MiniLM-L6-v2","logger":"sentence_transformers.SentenceTransformer"}
{"timestamp":"2025-07-03T17:33:47.769739","level":"info","event":"Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.","logger":"chromadb.telemetry.product.posthog"}
{"timestamp":"2025-07-03T17:33:47.908284Z","level":"info","event":"Generando resumen con el LLM local...","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-03T17:33:47.913577","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionError","exc_value":"HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff2d43bd70>: Failed to establish a new connection: [Errno 111] Connection refused'))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/rag_reporting_dag.py","lineno":39,"name":"summarize_task"},{"filename":"/opt/airflow/dags/reporting_pipeline.py","lineno":81,"name":"query_and_summarize"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py","lineno":3047,"name":"invoke"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py","lineno":378,"name":"invoke"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py","lineno":963,"name":"generate_prompt"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py","lineno":782,"name":"generate"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py","lineno":1028,"name":"_generate_with_cache"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_community/chat_models/ollama.py","lineno":291,"name":"_generate"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_community/chat_models/ollama.py","lineno":222,"name":"_chat_stream_with_aggregation"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_community/chat_models/ollama.py","lineno":194,"name":"_create_chat_stream"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/langchain_community/llms/ollama.py","lineno":252,"name":"_create_stream"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":115,"name":"post"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":700,"name":"send"}]},{"exc_type":"MaxRetryError","exc_value":"HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff2d43bd70>: Failed to establish a new connection: [Errno 111] Connection refused'))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":667,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}]},{"exc_type":"NewConnectionError","exc_value":"<urllib3.connection.HTTPConnection object at 0xffff2d43bd70>: Failed to establish a new connection: [Errno 111] Connection refused","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":445,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":276,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":213,"name":"_new_conn"}]},{"exc_type":"ConnectionRefusedError","exc_value":"[Errno 111] Connection refused","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":85,"name":"create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":73,"name":"create_connection"}]}]}
